Repository moonshotcollective/recruiter.party, pull requests merged in 2022-01, with the labels that each got.

#30 fix: Fix localhost cookie behaviour
  packages/server/config/development.js
  packages/server/config/production.js
  packages/server/config/staging.js
Labels: bug, enhancement

#48 Requests page
  packages/dapp/src/components/Profile/ApproveUnlock.tsx
  packages/dapp/src/components/Profile/RecruiterCard.tsx
  packages/dapp/src/components/layout/Navbar.tsx
  packages/dapp/src/pages/index.tsx
  packages/dapp/src/pages/requests.tsx
Labels: enhancement

#54 feat: Improve message signing behaviour
  packages/dapp/src/contexts/Web3Provider.tsx
Labels: enhancement

#65 Add start script for the dapp at project root
  package.json
  packages/dapp/package.json
Labels: bug

#73 fix: Fix unset owner value in mapping
  packages/hardhat-ts/contracts/DRecruitV1.sol
Labels: bug
